### ISSUE TITLE
Errors when importing plugin using manifest.json

### ISSUE THREAD

**Issue by teodesian** [katalon-studio/katalon-recorder#1]
Environment:
Firefox v 65.0
Chrome v 71.0.35

Steps to Reproduce:

1. Clone repository
2. Open about:debugging in Firefox
3. add temporary addon
4. Select the manifest.json in your clone of the repository

`Reading manifest: Error processing permissions.12: Value "debugger" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["bookmarks"], be one of ["find"], be one of ["history"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab", "tabs", "tabHide"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["browsingData"], be one of ["devtools"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["pkcs11"], be one of ["geckoProfiler"], be one of ["sessions"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
Reading manifest: Error processing offline_enabled: An unexpected property was found in the WebExtension manifest.`

I also got problems with chrome:

1. open chrome:extensions
2. toggle developer mode on
3. do "load unpacked"
4. select the directory you cloned the repo in

`Uncaught TypeError: Cannot read property 'fn' of undefined`
`content/jquery.simulate.js:17 (anonymous function)`

Not sure what that's about.

Nevertheless, it appears things load and run despite this?  Here's hoping it doesn't discourage people trying to work on this.

**Comment by devalex88** [comment]
Firefox was complaining about Chrome-only attributes. They were just warnings.

I'll take a look at the second error.

**Comment by kz0uat** [comment]
Hello, does anyone look at this issue?

**Comment by devalex88** [comment]
> Uncaught TypeError: Cannot read property 'fn' of undefined
content/jquery.simulate.js:17 (anonymous function)

The script `jquery.simulate.js` is needed for simulating jQuery UI's drag-and-drop function. If the website does not use jQuery, the above error will be thrown, but everything still works properly.
