### ISSUE TITLE
Unencoded special characters cause failures

### ISSUE THREAD

**Issue by jar452** [katalon-studio/katalon-recorder#106]
There is an issue with unencoded characters.
Create a suite that consists of 2 tests.
Each test will only have 2 steps: Step 1 open a page and Step 2 verify text that contains an ampersand.
Save your suite and delete it from the Katalon recorder.
Open the suite once again and Play the Full suite.
Test 1 will Pass and Test 2 will Fail.
This is because the ampersands appears as & amp ; (had to put spaces because github is fixing it)
Once again, delete the suite from the Katalon recorder.
Open the suite again, but this time, click on Test 2, then Play the Full suite.
This time, both tests will pass.  This is because when you click on Test 2, there is a "cleanse" that occurs
and you'll see that & amp ; now just appears as &
Can you fire this cleanse upon suite open, instead of upon clicking the test?
As a workaround, I click on every test in my suite before I run it, which is time consuming because I have close to 70 tests in my suite, but it does fix the issue.

**Comment by minhthanh3145** [comment]
Hi there, thank you for the bug report. We'll look into it and keep you updated when there's a fix.

**Comment by minhthanh3145** [comment]
@jar452 

This problem has been fixed in 5.6.2 which is available on Chrome store now. Please check it out and open another issue if the problem still persists! Thank you.
