### ISSUE TITLE
Can I copy part of your message to the Firefox reviewers?

### ISSUE THREAD

**Issue by toddtarsi** [katalon-studio/katalon-recorder#108]
I'm helping out on Selenium IDE and we just got the axe and your guys message really wraps up our situation too pretty well, so I want to copy part of that segment for our Readme as well.

How best can I copy that sentence and give you guys attribution? You seem like a cool group and I'd like to do this right :)

**Comment by toddtarsi** [comment]
Hey guys, I gave thanks in the commit message and changed the language to be unique. I hope this is sufficient. I'm just trying to deal with the mo hammer. Please let me know if there is anything else I could do to say thanks.

**Comment by coty** [comment]
More than sufficient. Glad we could help.
