### ISSUE TITLE
Error: call to eval() blocked by CSP

### ISSUE THREAD

**Issue by LiveLikeLastDay** [katalon-studio/katalon-recorder#12]
[info] Playing test case Daily check Katalon 2 / Entity Register
[info] Time: Tue Apr 02 2019 09:11:42 GMT+1100 (Australian Eastern Daylight Time) Timestamp: 1554156702770
[info] OS: Windows Version: 10
[info] Browser: Firefox Version: 66.0
[info] If the test cannot start, please refresh the active browser tab
**[error] Error: call to eval() blocked by CSP**
[info] Time: Tue Apr 02 2019 09:11:42 GMT+1100 (Australian Eastern Daylight Time) Timestamp: 1554156702855
[info] Test case failed

**Comment by devalex88** [comment]
Please try setting `security.csp.enable` to `false` in Firefox's `about:config`.
