### ISSUE TITLE
selectFrame does not work in katalon recorder plugin for chrome.

### ISSUE THREAD

**Issue by ashkaps** [katalon-studio/katalon-recorder#17]
I am trying to create a script that has an iframe.
I am using selectFrame command and have tried using the following ways in locator:
1. index=0
2. //iframe[@title='name']
3. xpath=//iframe[@title='name']

The log says 'Invalid Arguments'
I have tried recording and playing back and the script fails. 
I am using Chrome browser on Mac.

Plugin - 3.7.0
Chrome - 73.0.3683.
Mac OSX - Mojava 10.14.3

**Comment by devalex88** [comment]
I'm cleaning up stale issues - if you have any question please create new topics at https://forum.katalon.com.
