### ISSUE TITLE
How do I loop a script?

### ISSUE THREAD

**Issue by franchesko1437** [katalon-studio/katalon-recorder#19]
hello
How do I loop a script? to be carried out continuously

**Comment by alane019** [comment]
One way it to use LoadVars. And it will complete a loop for every
datapoints in the csv file you upload (in data menu). Outside of that, I
have not used loops, but I think there might be a loop command

**Comment by alane019** [comment]
> hello
> How do I loop a script? to be carried out continuously

See this reference for examples of loops with Katalon recorder: 
http://etverse.com/tech-ref/katalon-recorder/katalon-recorder-examples.html#while-loop
