### ISSUE TITLE
 Error: chrome is not defined

### ISSUE THREAD

**Issue by sumulige** [katalon-studio/katalon-recorder#2]
Hello, I git clone your code and can't start. Error: chrome is not defined, do you have a detailed startup document?

**Comment by devalex88** [comment]
You can follow instructions here https://developer.chrome.com/extensions/getstarted.

Open the Extension Management page by navigating to chrome://extensions.
The Extension Management page can also be opened by clicking on the Chrome menu, hovering over More Tools then selecting Extensions.
Enable Developer Mode by clicking the toggle switch next to Developer mode.
Click the LOAD UNPACKED button and select the extension directory.
