### ISSUE TITLE
derivative works license question

### ISSUE THREAD

**Issue by doggy8088** [katalon-studio/katalon-recorder#24]
I made a tool called [Protractor Recorder](https://github.com/doggy8088/protractor-recorder) that is based on your "Katalon Recorder". It's an open source software. Due to your recorder is not a MIT license, I'd like to confirm that is it okay to provide derivation work based on your software? If this is not allowed, I'll remove my project. Hope to get your response. Thanks!

**Comment by devalex88** [comment]
Thank you @doggy8088 for your question. You can keep and maintain your project. If possible, please consider contributing the changes back to this project.
