### ISSUE TITLE
Source code for PHPUnit formatter

### ISSUE THREAD

**Issue by tienvx** [katalon-studio/katalon-recorder#35]
Thanks for creating these great plugins (Katalon Recorder & PHPUnit formatter for Katalon Recorder).

I have some questions about PHPUnit formatter's source code:
* Is the source code for PHPUnit formatter for Katalon Recorder (created by Jan Esser) available? I searched github but I couldn't find it anywhere.
* I found this project https://github.com/vitormattos/Selenium-PHP-Formatter. Not sure how they are related, as that project quite old.
* If it's available, are there any chances for it to be merged into this project?

**Comment by devalex88** [comment]
Hi @tienvx,

We don't have/own the source code of the PHPUnit formatter plugin.

You can find it here https://bitbucket.org/inventis/phpunit-formatter-katalon-recorder.

**Comment by tienvx** [comment]
Thanks! The source code is on bitbucket, that's why I can't find it on github.

**Comment by Cellphonemega-LLC** [comment]
it sucks that you guys blocked the functionality of the plugin phpformatter. Dont waste your time downloading if you wanted to use php

**Comment by RestOp** [comment]
Any other recording tool for phpunit ?
