### ISSUE TITLE
KAT version seems not up to date?

### ISSUE THREAD

**Issue by pgroot91** [katalon-studio/katalon-recorder#36]
Hi Guys,

The version in GitHub seems out to date with the published version in the Chrome/Firefox store? 

Is the extension maintained somewhere else now?

Github: 3.9.0
Stores: 3.9.1

Can we still create PRs here on the Github project? 👍 

Patrick

**Comment by devalex88** [comment]
Thank you @pgroot91! The source code is still up-to-date. The 3.9.1 release was for a fix for Katalon Studio's recording function, and not for Katalon Recorder itself.

**Comment by pgroot91** [comment]
OK thanks! 👍 ll close the ticket then and continue to play around with current branch.
