### ISSUE TITLE
Can not import a test file 

### ISSUE THREAD

**Issue by AycaGozel** [katalon-studio/katalon-recorder#44]
I have a Katalon recorder test file  and I tried to import that file to the new pc. 
On the screen , I pushed file button and tried to import my test file as test document . There is no change on the screen or no errors.
![error](https://user-images.githubusercontent.com/53177426/68460147-f2aa9880-01bb-11ea-9f5d-6d9b82fcdede.png)

**Comment by olenitsj** [comment]
I have the same issue. 

Both Chome and firefox. 

saved test suite can't be opened.

**Comment by olenitsj** [comment]
@AycaGozel See my PR for the fix.
