### ISSUE TITLE
Dark arrow command unreadable

### ISSUE THREAD

**Issue by boriscosic** [katalon-studio/katalon-recorder#57]
macOS Catalina - Chrome

Only when clicking on the arrow the command menu is unreadable. On hover it looks fine.

<img width="597" alt="Screen Shot 2020-02-22 at 12 17 12 PM" src="https://user-images.githubusercontent.com/91231/75097931-a702db80-556d-11ea-9f6c-88e9f3c36e56.png">

**Comment by devalex88** [comment]
Thank you @boriscosic. This issue has been fixed on version 4.1.2.
