### ISSUE TITLE
export with Python show Unsupported command [dragAndDropToObject

### ISSUE THREAD

**Issue by 03128crz** [katalon-studio/katalon-recorder#60]
# ERROR: Caught exception [ERROR: Unsupported command [dragAndDropToObject | //div[@id='crowdPickMainArea']/div/div/div/div[2]/div/div | //div[@id='crowdPickConditionArea']/div/div]]

But I need the python scripts with the drag_and_drop method,I want  to know how katalon-recorder do this

**Comment by stoufa** [comment]
Hey @03128crz, I see that you closed the issue that you created within 10 days.
Can you please explain how did you manage to fix this issue?
I have a similar one:
```
# ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=0 | ]]
```
and it's blocking my Python script!
