### ISSUE TITLE
Unlock Feature popup is broken

### ISSUE THREAD

**Issue by tec-eric** [katalon-studio/katalon-recorder#90]
This popup appears every single time I run a script and it is breaking my automation.
The sign in link is broken (nothing happens when I click it)
The registration itself is broken (I used a separate email just to see if it would go away)
I click the maybe later link at the bottom and the popup appears the next time I run a script

At the moment, this chrome plugin is unusable. 
I have tried clearing cache and reinstalling the plugin without any success.

This started happening the other day (05/16) and there was an "update" this morning (05/18) and I was hoping it would fix this issue but it did not. I can't use this anymore so I am off to look for something else.

Anyone else having this issue?

![Katalon_Unlock_Features](https://user-images.githubusercontent.com/53630731/118670519-50aa3a00-b7bc-11eb-97cf-548286dfc006.jpg)

**Comment by minhthanh3145** [comment]
@tec-eric 

Hi, can you clarify what you mean by "registration is broken?" and "sign-in doesn't work". They are both working for me.

**Comment by tec-eric** [comment]
Thank you, to whoever fixed this. I was just now able to click the sign in tab and sign in.
