### ISSUE TITLE
not able to use shortcuts

### ISSUE THREAD

**Issue by 0140** [katalon-studio/katalon-recorder#91]

**Comment by 0140** [comment]
User not able to user shortcuts for

**Comment by minhthanh3145** [comment]
@0140 Hi there, we fixed this problem in 5.4.4. You can now use shortcuts in Target/Command/Value fields.

**Comment by 116581658** [comment]
Katalon Recorder: 5.4.4.: CTRL+Z doesn't work. If I paste a value in the Value field for instance with CTRL+V, I am not able to go back to the old value pressing on CTRL+Z.
